export const wellKnownInstruments: { [key: string]: string } = {
  piano: 'Piano',
  drums: 'Drums',
  guitar: 'Guitar',
  vocals: 'Vocals',
  keys: 'Keys',
  strings: 'Strings',
  horns: 'Horns',
  percussion: 'Percussion',
}

export const wellKnownVocalParts: { [key: string]: string } = {
  vocals: 'Vocals',
  other: 'Other',
  tenor: 'Tenor',
  t1: 'Tenor 1',
  t2: 'Tenor 2',
  t3: 'Tenor 3',
  bass: 'Bass',
  b1: 'Bass 1',
  b2: 'Bass 2',
  b3: 'Bass 3',
  alto: 'Alto',
  a1: 'Alto 1',
  a2: 'Alto 2',
  a3: 'Alto 3',
  soprano: 'Soprano',
  s1: 'Soprano 1',
  s2: 'Soprano 2',
  s3: 'Soprano 3',
  baritone: 'Baritone',
  countertenor: 'Countertenor',
  c1: 'Counter tenor 1',
  c2: 'Counter tenor 2',
  c3: 'Counter tenor 3',
  treble: 'Treble',
  solo: 'Solo',
}
