#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Fix from https://github.com/typicode/husky/issues/968#issuecomment-1176848345
exec >/dev/tty 2>&1

# Heavy checks should only be done on staged files
yarn lint-staged
